{{- if .Values.compass.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.compass.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.compass.name }}
    version: {{ .Values.compass.name }}
spec:
  replicas: {{ .Values.compass.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.compass.name }}
      version: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: '{{ .Values.compass.sidecarIstio.enabled }}' 
      labels:
        app: {{ .Values.compass.name }}
        version: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.compass.name }}
          image: {{ .Values.compass.image.tag }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP  
            initialDelaySeconds: 30
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1 
          imagePullPolicy: {{ .Values.compass.image.pullPolicy }}
          env:
          {{ range $i, $var := .Values.compass.envVars -}}
          - name: {{ $var.name | upper}}
            value: {{ $var.value | quote}}
          {{ end }}
          resources:
{{ toYaml .Values.compass.resources | indent 12 }}
      imagePullSecrets:
        - name: realwavelab-registry
    {{- with .Values.compass.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.compass.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.compass.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}