replicaCount: 1
envVars:
  - name: SPRING_PROFILES_ACTIVE
    value: "k8s"
  - name: DB_URL
    value: jdbc:postgresql://charles-postgresql:5432/darwinnotifications
  - name: DB_USERNAME
    value: postgres
  - name: DB_PASSWORD
    value: batatinha
  
  
appname: darwin-notifications

image:
  repository: darwin-notifications
  tag: realwavelab.azurecr.io/darwin-notifications:darwin-v-1-7-6
  blueTag: latest
service:
  name: darwin-notifications
  type: ClusterIP
  ports:
   - name: http
     port: 8080
configmaps:
  enabled: false
startcommand: 
  enabled: false
  value: "[\"/bin/sh\",\"-c\",\"/usr/sbin/nginx -c /data/darwin-ui-nginx.conf\"]"
ingress:
  enabled: false
  annotations: 
     kubernetes.io/ingress.class: nginx
     kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - name: zup.lab.realwave.zup.me
      port: http
  tls: 
    - secretName: lab-realwave-zupme
      hosts:
        - zup.lab.realwave.zup.me
resources:
   limits:
    cpu: 1
    memory: 1536Mi
   requests:
    cpu: 128m
    memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
imageCredentials:
  registry: realwavelab.azurecr.io
  username: realwavelab
  password: /uU7PBzXFzMlvlbQZWTHPAPqj38jfLV1
livenessProbe:
  enabled: true
  failureThreshold: 3
  httpGet:
    path: /actuator/health
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 120
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /actuator/health
    port: 8080
    scheme: HTTP  
  initialDelaySeconds: 120
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 1   

consulnode:
  enabled: false
  repository: realwave-node-consul
  path: /opt/darwin-ui/config

istio:
  enabled: true

vault:
  enabled: false
