apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appname }}
    version: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appname }}
      version: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: '{{ .Values.istio.enabled }}' 
      labels:
        app: {{ .Values.appname }}
        version: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceaccount | default "default" -}}
      {{ if .Values.consulnode.enabled }}
      initContainers:
        - name: consulnode-init
          image: "{{.Values.imageCredentials.registry}}/{{ .Values.consulnode.repository }}"
          # image: lukascaska/realwave-node-consul:v1
          volumeMounts:
            - name: consul-config
              mountPath: {{ .Values.consulnode.path }}  
          env:
          {{ range $i, $var := .Values.envVars -}}
          - name: {{ $var.name | upper}}
            value: {{ $var.value | quote}}
          {{ end }}
      {{ end }}
      containers:
        - name: {{ .Values.service.name }}
          image: "{{ .Values.image.tag }}"
          {{ if .Values.livenessProbe.enabled }}
          livenessProbe:
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.livenessProbe.httpGet.port }}
              scheme: {{ .Values.livenessProbe.httpGet.scheme }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          readinessProbe:
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.readinessProbe.httpGet.port }}
              scheme: {{ .Values.readinessProbe.httpGet.scheme }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          {{ end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{ if .Values.startcommand.enabled }}
          command: {{ .Values.startcommand.value }}
          {{ end }}
          env:
          {{ range $i, $var := .Values.envVars -}}
          - name: {{ $var.name | upper}}
            value: {{ $var.value | quote}}
          {{ end }}
          {{- if or (.Values.configmaps.enabled) (.Values.vault.enabled) (.Values.consulnode.enabled) -}}
          volumeMounts:
          {{ end }}
          {{ if .Values.configmaps.enabled }}
            - name: {{ .Release.Name }}-data
              mountPath: /data
          {{ end }}
          {{ if .Values.consulnode.enabled }}
            - name: consul-config
              mountPath: {{ .Values.consulnode.path }}
          {{ end }}          
          resources:
{{ toYaml .Values.resources | indent 12 }}
     {{ if or (.Values.configmaps.enabled) (.Values.vault.enabled) (.Values.consulnode.enabled) }}
      volumes:
     {{ end }}
     {{ if .Values.configmaps.enabled }}
      - name: {{ .Release.Name }}-data
        configMap:
          name: {{ .Release.Name }}-data
          defaultMode: 0700
     {{ end }}
     {{ if .Values.vault.enabled }}
      - name: app-creds
        emptyDir: {}
      - name: vault-token
        emptyDir: {}      
      {{ end }}
     {{ if .Values.consulnode.enabled }}
      - name: consul-config
        emptyDir: {}     
      {{ end }}
      imagePullSecrets:
      - name: {{ .Values.imageCredentials.username }}-registry
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
