name: build compass

on:
  push:
    branches: [main]
    paths:
      - "compass/**"
    tags:
      - "!*"
  pull_request:
    branches: [ main, charlescd-release-*.0 ]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "compass/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run actions checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Run Actions cache
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: actions/setup-go@331ce1d993939866bb63c32c6cbbfd48fa76fc57
        with:
          go-version: "^1.14.2"

      - name: Up Docker tests
        working-directory: ./compass
        run: make tests-dep-up

      - name: Run Unit tests
        working-directory: ./compass
        run: |
          go test -v -coverpkg ./internal/action,./internal/datasource,./internal/dispatcher,./internal/metric,./internal/metricsgroup,./internal/metricsgroupaction,./internal/moove,./internal/plugin ./internal/tests/ -coverprofile=coverage.cov

      - name: Tests coverage
        uses: codecov/codecov-action@29386c70ef20e286228c72b668a06fd0e8399192
        with:
          file: ./compass/coverage.cov
          flags: compass
          fail_ci_if_error: true
      - name: Horusec Security
        working-directory: ./compass
        env: 
          HORUSEC_CLI_REPOSITORY_AUTHORIZATION: ${{ secrets.HORUSEC_CLI_REPOSITORY_AUTHORIZATION }}
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
          horusec start -p . -n="Charles/compass" -u="https://api-horusec.zup.com.br"
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint install
        run: |
          download=https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh
          wget -O- -q $download |sudo sh -s -- -b /go/bin/ v1.42.0
      - name: lint files
        working-directory: ./compass
        run: |
          /go/bin/golangci-lint run
