#
  # Copyright 2020, 2021 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #  http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
#

name: build moove

on:
  push:
    branches: [ main ]
    paths:
      - 'moove/**'
    tags: 
      - '!*'
  pull_request:
    branches: [ main, charlescd-release-*.0 ]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'moove/**'

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run actions checkout
      uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # v2.3.5
    - name: Set up JDK 11
      uses: actions/setup-java@8db439b6b47e5e12312bf036760bbaa6893481ac # v2.3.1
      with:
        distribution: zulu
        java-version: 11
        cache: maven
    - name: Build
      run: mvn -B clean install
      working-directory: ./moove
    - name: Lint
      run: mvn antrun:run@ktlint
      working-directory: ./moove
    - name: Tests coverage
      uses: codecov/codecov-action@3082d5cdb8acdaf7816ef977efa4e2010ad3f013 # v1.5.2
      with:
        file: ./moove/**/target/site/jacoco/jacoco.xml
        flags: moove
        fail_ci_if_error: true
    - name: Horusec Security
      working-directory: ./moove
      env: 
        HORUSEC_CLI_REPOSITORY_AUTHORIZATION: ${{ secrets.HORUSEC_CLI_REPOSITORY_AUTHORIZATION }}
      run: |
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
        horusec start -p . -n="Charles/moove" -u="https://api-horusec.zup.com.br"
        
